domain: ""
domains:
    - api.openai.com
    - api.anthropic.com
certificates: []
apis:
    - name: gpt-5.4
      format: openai
      endpoint: http://example.com
      custom_model_id: gpt-5.4
      target_model_id: gpt-5.4
      stream_mode: ""
      custom_api_key: ""
      active: true
    - name: claude-sonnet-4-6
      format: anthropic
      endpoint: http://example.com
      custom_model_id: claude-sonnet-4-6
      target_model_id: claude-sonnet-4-6
      stream_mode: ""
      custom_api_key: kGl3sVgIWbj9TRqDlr7mHE5F8b66VKVk
      active: true
server:
    port: 443
    manage_port: 8080
    debug: true
