domain: api.openai.com
domains:
    - api.openai.com
    - api.anthropic.com
    - api3.cursor.sh
    - api2.cursor.sh
    - api.cursor.sh
    - cursor.sh
domain_enabled:
    api.anthropic.com: true
    api.cursor.sh: true
    api.openai.com: true
    api2.cursor.sh: true
    api3.cursor.sh: true
    cursor.sh: true
certificates: []
apis:
    - name: 3R-GPT
      format: openai
      endpoint: https://code.ppchat.vip
      custom_model_id: gpt-5.4
      target_model_id: gpt-5.3-codex
      stream_mode: "false"
      custom_api_key: 
      active: true
    - name: 3R-Claude
      format: anthropic
      endpoint: https://code.3rcd.com
      custom_model_id: claude-sonnet-4-6
      target_model_id: claude-sonnet-4-6
      stream_mode: ""
      custom_api_key: ""
      active: true
server:
    port: 443
    manage_port: 8080
    debug: true
